config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'

  get 'help'        => 'static_pages#help'
  get 'about'       => 'static_pages#about'
  get 'contact'     => 'static_pages#contact'
  get 'signup'      => 'users#new'
  get 'login'       => 'sessions#new'
  post 'login'      => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'

  resources :users
  resources :projects, except: :index do
    resources :task_lists
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :task_lists, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 140 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "Project created!"
      redirect_to root_url
    else
      @project_list = []
      render 'static_pages/home'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      flash[:success] = "Information Updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    flash[:success] = "Project deleted"
    redirect_to request.referrer || root_url
  end

  private

    def project_params
      params.require(:project).permit(:title, :description)
    end

    def correct_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to root_url if @project.nil?
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">
  <span class="title"><%= link_to project.title, project %></span>
  <span class="description"><%= project.description %></span>
  <span class="user">Project Admin: <%= project.user.name %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(project.created_at) %> ago.
    <% if current_user?(project.user) %>
      <%= link_to 'delete', project, method: :delete, data: {confirm: "You sure?" } %> | 
      <%= link_to 'edit', edit_project_path(project) %>
    <% end %>
  </span>
</li>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>
<h1>Edit Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>
  </div>  
</div>

app/views/projects/show.html.erb
<div class="project">
  <div class="project-info">
    <li id="project-<%= @project.id %>">
      <span class="title"><%= @project.title %></span>
      <span class="description"><%= @project.description %></span>
      <span class="user">Project Admin: <%= link_to @project.user.name, @project.user %></span>
      
      <span class="timestamp">
        Created <%= time_ago_in_words(@project.created_at) %> ago.
        <% if current_user?(@project.user) %>
          <%= link_to 'delete', @project, method: :delete, data: {confirm: "You sure?" } %> | 
          <%= link_to 'edit', edit_project_path(@project) %>
        <% end %>
      </span>
    </li>
  </div>
  <div class="navbar">
    <ul class="nav navbar-nav">
      <li><%= link_to "Task Lists", project_task_lists_path(@project) %></li>
      <li><%= link_to "Discussions", '#' %></li>
    </ul>    
  </div>
  <div class="summary">
    This will contain a visual summary for the project. It will have latest updates, lastest discussions, task lists, files, etc.
  </div>
</div>

 