config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'

  get 'help'        => 'static_pages#help'
  get 'about'       => 'static_pages#about'
  get 'contact'     => 'static_pages#contact'
  get 'signup'      => 'users#new'
  get 'login'       => 'sessions#new'
  post 'login'      => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'

  resources :users
  resources :projects, except: :index do
    resources :task_lists
  end

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: true, length: { maximum: 140 }
  validates :project_id, presence: true


  private

    def get_task_lists(project)
      self.find_by(project_id: project.id)
    end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :logged_in_user
  before_action :current_project

  def new
    @task_list = TaskList.new
  end

  def create
    @task_list = current_project.task_lists.build(task_list_params)
    if @task_list.save
      flash[:success] = "Task List created!"
      redirect_to project_task_lists_path(current_project)
    else
      render 'new'
    end
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def index
    @task_lists = TaskList.where(project_id: params[:project_id])
  end

  def edit
    @task_list = TaskList.find(params[:id])
  end

  def update
    @task_list = TaskList.find(params[:id])

    if @task_list.update_attributes(task_list_params)
      flash[:success] = "Information Updated"
      redirect_to project_task_list_url(current_project, @task_list)
    else
      render 'edit'
    end 
  end

  def destroy
    @task_list = TaskList.find(params[:id])
    @task_list.destroy
    flash[:success] = "Task List deleted"
    redirect_to current_project
  end

  private

    def task_list_params
      params.require(:task_list).permit(:name)
    end

    def current_project
      @project = Project.find(params[:project_id])
    end

end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_task_list.html.erb
<li>
  <%= link_to task_list.name, project_task_list_path(@project, task_list.id) %>
</li>

app/views/task_lists/edit.html.erb
<h1><%= @project.title %></h1>

<h3>Edit Task List</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task_list, url: project_task_list_path(@project, @task_list)) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/task_lists/index.html.erb
<% provide(:title, @project.title) %>

<h1><%= @project.title %></h1>

<div class="tasklists">
  
  <div class="name">
    <h3>Task Lists</h3>
  </div>

  <div class="row">
    <div class="col-md-8">
      <ul class="task_list">
        <%= render @task_lists %>
      </ul>
    </div>
    <aside class="col-md-4">
      <div>
      <%= link_to "Add a task list", new_project_task_list_path(@project) %>
      </div>
      <div>
        <h5>Current task lists</h5>
      </div>
      <div>
        <h5>Completed task lists</h5>
      </div>
    </aside>
  </div>

</div>

app/views/task_lists/new.html.erb
<h1><%= @project.title %></h1>

<h3>Add Task List</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task_list, url: project_task_lists_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Add task list", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/task_lists/show.html.erb
<h1><%= @project.title %></h1>
<h3><%= @task_list.name %></h3>

<%= link_to 'Edit Task List', edit_project_task_list_path(@project, @task_list) %> | 
<%= link_to "Delete", project_task_list_path(@project, @task_list), method: :delete, data: { confirm: "You sure?" } %>